function [Hd, b, a] = designLowPassFilter_IIR(Fs,Fpass,Fstop)
%FILTER_LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 25-Nov-2014 09:37:24

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs = 24000;  % Sampling Frequency
% Fpass = 4000;              % Passband Frequency
% Fstop = 6000;              % Stopband Frequency
Dpass = 0.0057563991496;   % Passband Ripple
Dstop = 3.1622776602e-08;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
a = 1;
Hd = dfilt.dffir(b);

% [EOF]

